GET http://localhost:3001/users/getAll
// GET http://localhost:3001/users/getAll/1

####
POST http://localhost:3001/users/register
Content-Type: application/json

{
    "lastName": "John",
    "firstName": "Doe",
    "email": "jo@gmail.com",
    "password": "jhon@gmail.com"
}

####
POST http://localhost:3001/users/login
Content-Type: application/json

{
    "lastName": "John",
    "firstName": "Doe",
    "email": "jo@gmail.com",
    "password": "jhon@gmail.com"
}